// ignore_for_file: constant_identifier_names

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// This file is normally generated by the FlutterFire CLI.
/// Run `flutterfire configure` and replace the placeholder values below
/// with the configuration of your Firebase project.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG-AaPfJCFrNevCDywkV9XeUy6egc3e1Y',
    appId: '1:1043144726360:web:369a191dc25af2608df72d',
    messagingSenderId: '1043144726360',
    projectId: 'lebondeal-baf79',
    authDomain: 'lebondeal-baf79.firebaseapp.com',
    storageBucket: 'lebondeal-baf79.firebasestorage.app',
    measurementId: 'G-97RPCPHCTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-AaPfJCFrNevCDywkV9XeUy6egc3e1Y',
    appId: '1:1043144726360:android:369a191dc25af2608df72d',
    messagingSenderId: '1043144726360',
    projectId: 'lebondeal-baf79',
    storageBucket: 'lebondeal-baf79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG-AaPfJCFrNevCDywkV9XeUy6egc3e1Y',
    appId: '1:1043144726360:ios:369a191dc25af2608df72d',
    messagingSenderId: '1043144726360',
    projectId: 'lebondeal-baf79',
    storageBucket: 'lebondeal-baf79.firebasestorage.app',
    iosBundleId: 'com.example.lebondeal',
  );
}
